#!/bin/bash

# find how many CPUs are available
cpu=`cat /proc/cpuinfo | grep -c "processor"`

# clear build path and cd to it
rm -rf openbabel-build
mkdir openbabel-build
cd openbabel-build

cmake ../openbabel \
-DRUN_SWIG=ON \
-DPHP_BINDINGS=ON \
-DPYTHON_BINDINGS=ON \
-DCMAKE_BUILD_TYPE=RELEASE

make -j ${cpu}
make test
